#!/usr/bin/env node
/**
 * Fetch the webfonts the site uses and self-host them.
 *
 * Reads the Google Fonts CSS (which lists one @font-face per subset), keeps the
 * latin subset of every family/style requested, downloads those woff2 files
 * into assets/fonts/ and writes assets/css/fonts.css with local URLs - so the
 * site never talks to fonts.googleapis.com at runtime.
 *
 * Both families are variable fonts: Source Serif 4 carries opsz + wght (roman
 * and italic), Fraunces carries opsz + wght. One woff2 per style is enough.
 *
 *   node tools/fetch-fonts.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = join(ROOT, "assets/fonts");
const CSS_OUT = join(ROOT, "assets/css/fonts.css");

const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const GF = "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,100..900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap";

// only the latin subset: the site's copy is English
const WANTED_SUBSET = "latin";

const css = await (await fetch(GF, { headers: { "User-Agent": UA } })).text();

// Google emits "/* subset */" comments before each @font-face block
const blocks = [];
const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
let m;
while ((m = re.exec(css))) blocks.push({ subset: m[1], block: m[2] });

const keep = blocks.filter((b) => b.subset === WANTED_SUBSET);
if (keep.length === 0) {
  console.error("fetch-fonts: no latin @font-face blocks found - Google's CSS format changed?");
  process.exit(1);
}

mkdirSync(FONT_DIR, { recursive: true });
const out = [
  "/* Self-hosted webfonts. Generated by tools/fetch-fonts.mjs - do not edit.",
  "   Google Fonts is the source; nothing is requested from it at runtime. */",
  "",
];

for (const { block } of keep) {
  const family = /font-family:\s*'([^']+)'/.exec(block)[1];
  const style = /font-style:\s*([a-z]+)/.exec(block)[1];
  const subset = WANTED_SUBSET;
  const url = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(block)[1];
  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${style}-${subset}.woff2`;

  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(join(FONT_DIR, slug), buf);

  const weightRange = /font-weight:\s*([0-9]+(?:\s+[0-9]+)?)/.exec(block)[1];
  out.push(
    `@font-face {`,
    `    font-family: '${family}';`,
    `    font-style: ${style};`,
    `    font-weight: ${weightRange};`,
    `    font-display: swap;`,
    `    src: url('/assets/fonts/${slug}') format('woff2');`,
    `}`,
    ``
  );
  console.log(`${slug}  ${(buf.length / 1024).toFixed(1)} KB  (${family} ${style} ${weightRange})`);
}

writeFileSync(CSS_OUT, out.join("\n"));
console.log(`\nwrote ${CSS_OUT} (${keep.length} @font-face rules)`);
